version: '3'

services:
    app:
        image: nginx:latest
        volumes:
            - ./app:/var/www/html
            - ./conf:/etc/nginx/conf.d/
        ports:
            - 8080:80
        depends_on:
            - phpfpm

    phpfpm:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - CONSUL_URL=${CONSUL_URL}
        volumes:
            - ./app:/var/www/html
            - ./templates:/templates
        ports:
            - 9000:9000

    consul-template:
        image: hashicorp/consul-template:alpine
        container_name: "consul-template"
        volumes:
         - "./consul:/data"
         - "./app:/app"
        environment:
            - CONSUL_URL=${CONSUL_URL}
        command: consul-template -config /data/template.hcl -consul-addr ${CONSUL_URL}
